# config.py

# --- YOUR CREDENTIALS ---
CLIENT_ID = "4563NFHBGF-100"
SECRET_KEY = "SG724LR1OA"
REDIRECT_URI = "https://trade.fyers.in/api-report/redirect/fyers/"

# Paste your fresh auth_code from the browser URL here
# You get this by running auth.py in your terminal
AUTH_CODE = "AUTH_CODE =https://trade.fyers.in/api-report/redirect/fyers/?s=ok&code=200&auth_code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI0NTYzTkZIQkdGIiwidXVpZCI6IjEzOTczZmU0ODU0OTQyYWNhY2E0ZTZhZDNjNTVhNGQ3IiwiaXBBZGRyIjoiIiwibm9uY2UiOiIiLCJzY29wZSI6IiIsImRpc3BsYXlfbmFtZSI6IlhBMTI0MzgiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiJlNTY0MmZjNTEyMTZjNTU5ZmM2YTJkMDUzNTYyNzdjNTAwNmU2NTc2NDYxZWQwZGRjMGI5ZWViNSIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImF1ZCI6IltcImQ6MVwiLFwiZDoyXCIsXCJ4OjBcIixcIng6MVwiXSIsImV4cCI6MTc3NjMwNDM3NiwiaWF0IjoxNzc2Mjc0Mzc2LCJpc3MiOiJhcGkubG9naW4uZnllcnMuaW4iLCJuYmYiOjE3NzYyNzQzNzYsInN1YiI6ImF1dGhfY29kZSJ9.P6bIeBgNGeHNpkJdicxcWaIbItS7gSZ_TomZWAVtkGE&state=None" 

# We start with 5 stocks for testing. We will expand to 50 later.
# Replace the old NIFTY_SYMBOLS with this:
NIFTY_SYMBOLS = [
    "NSE:ADANIENT-EQ", "NSE:ADANIPORTS-EQ", "NSE:APOLLOHOSP-EQ", "NSE:ASIANPAINT-EQ", 
    "NSE:AXISBANK-EQ", "NSE:BAJAJ-AUTO-EQ", "NSE:BAJFINANCE-EQ", "NSE:BAJAJFINSV-EQ", 
    "NSE:BPCL-EQ", "NSE:BHARTIARTL-EQ", "NSE:BRITANNIA-EQ", "NSE:CIPLA-EQ", 
    "NSE:COALINDIA-EQ", "NSE:DIVISLAB-EQ", "NSE:DRREDDY-EQ", "NSE:EICHERMOT-EQ", 
    "NSE:GRASIM-EQ", "NSE:HCLTECH-EQ", "NSE:HDFCBANK-EQ", "NSE:HDFCLIFE-EQ", 
    "NSE:HEROMOTOCO-EQ", "NSE:HINDALCO-EQ", "NSE:HINDUNILVR-EQ", "NSE:ICICIBANK-EQ", 
    "NSE:ITC-EQ", "NSE:INDUSINDBK-EQ", "NSE:INFY-EQ", "NSE:JSWSTEEL-EQ", 
    "NSE:KOTAKBANK-EQ", "NSE:LT-EQ", "NSE:M&M-EQ", 
    "NSE:MARUTI-EQ", "NSE:NTPC-EQ", "NSE:NESTLEIND-EQ", "NSE:ONGC-EQ", 
    "NSE:POWERGRID-EQ", "NSE:RELIANCE-EQ", "NSE:SBILIFE-EQ", "NSE:SBIN-EQ", 
    "NSE:SUNPHARMA-EQ", "NSE:TCS-EQ", "NSE:TATACONSUM-EQ", 
    "NSE:TATASTEEL-EQ", "NSE:TECHM-EQ", "NSE:TITAN-EQ", "NSE:ULTRACEMCO-EQ", 
    "NSE:UPL-EQ", "NSE:WIPRO-EQ"
]